language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - sudo apt update
  - pip install requiremtents.txt
  - git clone https://github.com/arezaii/pf_tools
  - cd pf_tools/pfio
  - pip install .
  - cd ../pf_fort_io
  - pip install .
  - cd ../tests
# command to run tests
script:
  - python -m unittest discover -p '*_tests.py'